package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-05-05T13:15:01.655+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://webservice/", name = "Calculator")
public interface Calculator {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice/", className = "webservice.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice/", className = "webservice.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "multiply", targetNamespace = "http://webservice/", className = "webservice.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://webservice/", className = "webservice.MultiplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );
}
